### ISSUE TITLE
403 forbidden问题可以怎么解决

### ISSUE THREAD

**Issue by dd123-a** [desonglll/JavlibraryCrawler#1]
你好，2023-10-09 15:06:38 [scrapy.core.engine] DEBUG: Crawled (403) <GET https://www.javlibrary.com/cn/vl_star.php?list&mode=&s=ae5q6&page=1> (referer: None)，可以怎么绕过，我尝试修改过user agent，还是没办法爬取

**Comment by desonglll** [comment]
你好，可以试试不同地区的代理，JP、TW或US。我在JP下测试正常

**Comment by dd123-a** [comment]
> 你好，可以试试不同地区的代理，JP、TW或US。我在JP下测试正常

问题解决了，或许需要自己更新对应的user agent才可以，我第一次更新的user agent是在谷歌浏览器获取的，第二次则是联想浏览器，这是唯一的不同了，不知道为什么前者不行，后者可以。顺便问一下为什么不顺便获得磁力链接，是不允许还是没有实现呢。

**Comment by desonglll** [comment]
> > 你好，可以试试不同地区的代理，JP、TW或US。我在JP下测试正常
> 
> 问题解决了，或许需要自己更新对应的user agent才可以，并不遵守他的规则。顺便问一下为什么不顺便获得磁力链接，是不允许还是没有实现呢。

最近在准备考研，打算考完试之后时间充裕再实现🥹

**Comment by dd123-a** [comment]
> > > 你好，可以试试不同地区的代理，JP、TW或US。我在JP下测试正常
> > 
> > 
> > 问题解决了，或许需要自己更新对应的user agent才可以，并不遵守他的规则。顺便问一下为什么不顺便获得磁力链接，是不允许还是没有实现呢。
> 
> 最近在准备考研，打算考完试之后时间充裕再实现🥹

哈哈哈好的，祝你成功。
